# Generated by Django 4.2.13 on 2024-12-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        
    ]
